services:
  service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filmsbase
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - service-db:/var/lib/postgresql/data
    ports:
      - 6000:5432
    networks:
      - mynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d filmsbase"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./videohub-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      BACKEND_DOCKER_FILE: /app/docker-compose.yml
      STORAGE_DIR: /app
      LOG_FILENAME: /app/logs.txt
      POSTGRES_URL: jdbc:postgresql://service-db/filmsbase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - mynet

  frontend:
    build:
      context: ./videohub-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  service-db:
  frontend:
  backend:

networks:
  mynet:
    driver: bridge